services:
  postgres:
    image: postgres:15-alpine
    container_name: altaa-postgres
    restart: no
    environment:
      POSTGRES_DB: altaadb
      POSTGRES_USER: altaa_user
      POSTGRES_PASSWORD: essaeumasenhadetesteapenasparatestesdetestesdosistema
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: altaa-backend
    restart: no
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://altaa_user:essaeumasenhadetesteapenasparatestesdetestesdosistema@postgres:5432/altaadb
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run build && npm start

  prisma-studio:
    container_name: altaa-prisma-studio
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    command: npx prisma studio --port 5555 --hostname 0.0.0.0
    ports:
      - "5555:5555"
    depends_on:
      - postgres

volumes:
  pgdata:
